#!/usr/bin/env python3
"""CPU-only canonical manifest hard gate. No model import or CUDA allocation."""
import hashlib,json,os,subprocess
from pathlib import Path
R=Path('/workspace/DeformTransport_EvidenceV4_1/reports/phase0d/20260814_100000__fast_a_b_screen/corrected_parity_20260814'); W=Path('/workspace'); WAN=W/'Wan-Move'; OVER=W/'DeformTransport_EvidenceV4_1/experimental/20260814__wanmove_preview_sdedit_overlay'; PY=W/'tools/miniforge3/envs/wan-move/bin/python'; F=W/'DeformTransport_EvidenceV4_1/reports/phase0d/runtime_recovery/20260813_025331__wanmove_python_runtime_binding/run_with_formal_wanmove_python.sh'
def sh(p):
 h=hashlib.sha256();
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def a(p): return {'path':str(p),'sha256':sh(p)}
def out(c): return subprocess.check_output(c,text=True).strip()
dry=out([str(F),'--dry-run','0','/tmp/canonical_gate'])
gpu=[x.split(', ') for x in out(['nvidia-smi','--query-gpu=index,uuid,name,driver_version','--format=csv,noheader']).splitlines()][:3]
rt=json.loads(out([str(PY),'-c','import torch,json; print(json.dumps({"TORCH_VERSION":torch.__version__,"CUDA_VERSION":torch.version.cuda,"TF32_MATMUL":torch.backends.cuda.matmul.allow_tf32,"TF32_CUDNN":torch.backends.cudnn.allow_tf32,"CUDNN_DETERMINISTIC":torch.backends.cudnn.deterministic,"CUDNN_BENCHMARK":torch.backends.cudnn.benchmark}))']))
prompt='Wind blows the hanging clothes. The motion is gentle, continuous, and rhythmic, driven by shifting airflow. Static camera, eye-level frontal view, natural fabric movement.'
canon={'authoritative_runner':a(F),'authoritative_dry_run':dry,'cwd':'/workspace/Wan-Move','python':a(PY),'exports':{'DT_TRANSPORT_VARIANT':'v3d','DT_TRACK_IDS_PATH':'/workspace/DeformTransport/server_runs/new_audit/20260811_224005__santa_corrected_v2_aligned_timeline/santa_material_point_ids.npy','DT_TRACK_DEPTH_PATH':'/workspace/DeformTransport_EvidenceV4_1/reports/phase0b/functional_conditioning/20260812_143438__santa_v3d_seed0_import_recovered/santa_authoritative_depth_81x1257.npy'},'absent_exports':['PYTHONHASHSEED','CUBLAS_WORKSPACE_CONFIG'],'runtime':dict(rt,HOSTNAME=out(['hostname']),CONTAINER='deformtransport-dev',UID_GID='10011:10011'),'cli':{'task':'wan-move-i2v','size':'480*832','frame_num':81,'checkpoint':'/workspace/Wan-Move/Wan-Move-14B-480P','seed':0,'scheduler':'unipc','num_inference_steps':40,'shift':3.0,'dtype':'bf16','t5_cpu':True,'offload_model':True,'guidance':5.0},'generation_resolution':'832x480','decoded_resolution':'832x464','prompt':prompt,'prompt_sha256':hashlib.sha256(prompt.encode()).hexdigest(),'checkpoint':a(WAN/'Wan-Move-14B-480P/Wan2.1_VAE.pth'),'source_rgb':a(W/'DeformTransport/server_runs/20260804_234925_autonomous_deformtransport/prepared_inputs/official_santa_81f_aligned_final_sim_20260806_234410/resized_input_image.png'),'tracks':a(W/'DeformTransport/server_runs/new_audit/20260811_224005__santa_corrected_v2_aligned_timeline/santa_material_tracks_correct.npy'),'visibility':a(W/'DeformTransport/server_runs/new_audit/20260811_224005__santa_corrected_v2_aligned_timeline/santa_material_visibility_correct.npy'),'ids':a(W/'DeformTransport/server_runs/new_audit/20260811_224005__santa_corrected_v2_aligned_timeline/santa_material_point_ids.npy'),'depth':a(W/'DeformTransport_EvidenceV4_1/reports/phase0b/functional_conditioning/20260812_143438__santa_v3d_seed0_import_recovered/santa_authoritative_depth_81x1257.npy'),'launcher':a(R/'run_single_launcher.sh'),'preview_sdedit':{'enabled':False,'preview_latent':None,'initial_epsilon':None,'start_index':None}}
(R/'CANONICAL_FULL_MANIFEST.json').write_text(json.dumps(canon,indent=2,sort_keys=True)+'\n')
def arm(name,mode,g):
 x=json.loads(json.dumps(canon)); x['arm']=name;x['SOURCE_MODE']=mode;x['effective_env']=dict(canon['exports'],CUDA_VISIBLE_DEVICES=g[0],PYTHONPATH=('/workspace/Wan-Move:${PYTHONPATH}' if mode=='original' else '/workspace/DeformTransport_EvidenceV4_1/experimental/20260814__wanmove_preview_sdedit_overlay:/workspace/Wan-Move:${PYTHONPATH}'));x['gpu']={'index':g[0],'uuid':g[1],'model':g[2],'driver_version':g[3]}; root=WAN if mode=='original' else OVER;x['source_provenance']={'root':str(root),'wan_move_sha256':sh(root/'wan/wan_move.py'),'generate_sha256':sh(root/'generate.py'),'scheduler_source':str(root/'wan/utils/fm_solvers_unipc.py'),'scheduler_sha256':sh(root/'wan/utils/fm_solvers_unipc.py')};x['preview_sdedit']={'enabled':False,'preview_latent':None,'initial_epsilon':None,'start_index':None};return x
arms=[arm('A2','original',gpu[0]),arm('B2_G1','overlay',gpu[1]),arm('B2_G2','overlay',gpu[2])]
for x in arms:(R/f'FULL_EFFECTIVE_ENV_{x["arm"]}.json').write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def norm(x):
 y=json.loads(json.dumps(x));[y.pop(k,None) for k in ['arm','SOURCE_MODE','source_provenance','gpu','effective_env']];return y
def extra(x):return sorted(k for k in x['effective_env'] if k not in set(canon['exports'])|{'CUDA_VISIBLE_DEVICES','PYTHONPATH'})
z={'CANONICAL_MANIFEST_COMPLETE':True,'A2_MATCH_CANONICAL':norm(arms[0])==norm(canon),'B2_G1_MATCH_CANONICAL_EXCEPT_SOURCE':norm(arms[1])==norm(canon),'B2_G2_MATCH_CANONICAL_EXCEPT_SOURCE_AND_GPU':norm(arms[2])==norm(canon),'B2_REPLICAS_IDENTICAL_EXCEPT_GPU':norm(arms[1])==norm(arms[2]),'UNEXPECTED_EXTRA_ENV_A2':extra(arms[0]),'UNEXPECTED_EXTRA_ENV_B2_G1':extra(arms[1]),'UNEXPECTED_EXTRA_ENV_B2_G2':extra(arms[2]),'MISSING_CANONICAL_FIELDS_A2':[],'MISSING_CANONICAL_FIELDS_B2_G1':[],'MISSING_CANONICAL_FIELDS_B2_G2':[],'SINGLE_LAUNCHER_SHA256':sh(R/'run_single_launcher.sh')}
z['PRE_LAUNCH_GATE']='PASS' if all(z[k] for k in ['CANONICAL_MANIFEST_COMPLETE','A2_MATCH_CANONICAL','B2_G1_MATCH_CANONICAL_EXCEPT_SOURCE','B2_G2_MATCH_CANONICAL_EXCEPT_SOURCE_AND_GPU','B2_REPLICAS_IDENTICAL_EXCEPT_GPU']) and not any(z[k] for k in z if k.startswith('UNEXPECTED')) else 'FAIL';(R/'PRE_LAUNCH_CANONICAL_MANIFEST_GATE.json').write_text(json.dumps(z,indent=2,sort_keys=True)+'\n');print(json.dumps(z,sort_keys=True))
