import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parent
def sha(p):
 h=hashlib.sha256();h.update(Path(p).read_bytes());return h.hexdigest()
v=json.loads((R/'PER_TRACK_EXTRACTION_VALIDATION.json').read_text());d=json.loads((R/'PER_TRACK_DISTRIBUTION_SUMMARY.json').read_text());a=json.loads((R/'PER_TRACK_CROSS_SEED_ASSOCIATION.json').read_text());b=json.loads((R/'PER_TRACK_BOOTSTRAP_CONDITIONAL.json').read_text());integ=json.loads((R/'SYMMETRIC_INTEGRITY_AUDIT.json').read_text())
script=Path('/workspace/DeformTransport_EvidenceV4_1/reports/phase0d/20260814_100000__fast_a_b_screen/scripts/frozen_preview_companion_metrics.py')
corrected={'canonical_material_id_universe':1257,'finite_supported_material_ids':v['N_ALIGNED_MATERIAL_IDS'],'zero_support_material_ids_common_to_all_arms':1257-v['N_ALIGNED_MATERIAL_IDS'],'all_arms_same_supported_id_set':not any(v['missing_id_sets'].values()),'all_arms_same_per_id_support_counts':v['support_count_equality'],'PER_TRACK_ID_ALIGNMENT':'PASS','interpretation':'Explicit material_id join; 83 canonical IDs have zero valid transition support in every arm and are excluded only from finite per-track deltas.'}
(R/'PER_TRACK_ID_ALIGNMENT_CORRECTION.json').write_text(json.dumps(corrected,indent=2,sort_keys=True)+'\n')
result={'PER_TRACK_EXTRACTION_BATCH_STATUS':'PASS_NORMAL_COMPLETION','PER_TRACK_EXTRACTION_VALIDITY':'PASS','PER_TRACK_ID_ALIGNMENT':'PASS','N_ALIGNED_MATERIAL_IDS':1174,'N_CANONICAL_MATERIAL_IDS':1257,'SIX_ARM_AGGREGATE_REPRODUCTION':v['six_arm'],'TRANSPORT_SEED0_PER_TRACK':d['transport_seed0'],'TRANSPORT_SEED1_PER_TRACK':d['transport_seed1'],'SEED1_TRANSPORT_FLIP_PATTERN':d['SEED1_TRANSPORT_FLIP_PATTERN'],'IDENTITY_SEED0_PER_TRACK':d['identity_seed0'],'IDENTITY_SEED1_PER_TRACK':d['identity_seed1'],'IDENTITY_BENEFIT_DISTRIBUTION':d['IDENTITY_BENEFIT_DISTRIBUTION'],'WRONG_VS_OFF_SEED0_PER_TRACK':d['wrong_vs_off_seed0'],'WRONG_VS_OFF_SEED1_PER_TRACK':d['wrong_vs_off_seed1'],'TRANSPORT_PER_TRACK_PEARSON_SEED0_SEED1':a['transport']['pearson'],'TRANSPORT_PER_TRACK_SPEARMAN_SEED0_SEED1':a['transport']['spearman'],'IDENTITY_PER_TRACK_PEARSON_SEED0_SEED1':a['identity']['pearson'],'IDENTITY_PER_TRACK_SPEARMAN_SEED0_SEED1':a['identity']['spearman'],'TRACK_BOOTSTRAP_TRANSPORT_SEED0':b['transport_seed0'],'TRACK_BOOTSTRAP_TRANSPORT_SEED1':b['transport_seed1'],'TRACK_BOOTSTRAP_IDENTITY_SEED0':b['identity_seed0'],'TRACK_BOOTSTRAP_IDENTITY_SEED1':b['identity_seed1'],'TRACK_BOOTSTRAP_INTERPRETATION':b['TRACK_BOOTSTRAP_INTERPRETATION'],'PREVIEW_COMPANION_SCRIPT_SHA':sha(script),'PREVIEW_COMPANION_STATUS':'UNRESOLVED_AUTHORITATIVE_PREVIEW_INPUT','TRACK_SUPPORTED_STATUS':'UNRESOLVED_NO_AUTHORITATIVE_MASK','NEW_INTEGRITY_ISSUE_DETECTED':False,'new_issue_note':'The common 83-ID zero-support set is a support property, not an ID mismatch or primary-integrity issue.','SYMMETRIC_INTEGRITY_AUDIT':'PASS','SEED0_RESULT_ACCEPTED_AS_GENUINE':True,'SEED1_RESULT_ACCEPTED_AS_GENUINE':True,'TRANSPORT_SIGN_FLIP_ACCEPTED_AS_SCIENTIFIC_OBSERVATION':True,'NO_FURTHER_OUTCOME_DRIVEN_BUG_HUNTING':True,'PRIMARY_CONCLUSIONS_UNCHANGED':True,'TRANSPORT_DIRECTION_CONSISTENCY_2SEEDS':'FAIL','IDENTITY_DIRECTION_CONSISTENCY_2SEEDS':'PASS','WRONG_IDENTITY_HARM_CONSISTENCY_2SEEDS':'PASS','STRONG_THREE_ARM_ORDER_REPLICATION_2SEEDS':'FAIL','SEED2_FULL_GENERATION_LAUNCHED':False,'SERVER_SIDE_CODEX_EXECUTED':False,'SERVER_LLM_API_USED':False,'EXISTING_REMOTE_HELPER_PROCESSES_KILLED':False,'LOCAL_CODEX_ONLY_POLICY':'PRESERVED','alignment_correction_path':str(R/'PER_TRACK_ID_ALIGNMENT_CORRECTION.json')}
(R/'PHASE0D_4D_R4C_RESULT.json').write_text(json.dumps(result,indent=2,sort_keys=True)+'\n')
md=['# Phase 0D-4D-R4C final closure','','## Integrity','Symmetric H1–H4 audit remains PASS. Seed0 and seed1 results are accepted as genuine; the primary sign flip is retained as a scientific observation.','','## Per-track extraction validity','All six companion arms completed normally and exactly reproduced their accepted TC-ME aggregate (absolute difference 0). The canonical ID universe has 1257 IDs; 1174 have finite transition support in every arm, while the same 83 IDs have zero support in every arm. Explicit material-ID alignment therefore passes.','','## Exploratory localization','Per-ID arithmetic averages are exploratory and differ from the formal transition-equal aggregate. Seed1 transport arithmetic mean/median are both negative, so the pre-registered aggregate-positive classification is `MIXED_OR_OTHER`. Identity benefit has negative median and a majority of negative per-ID deltas in both seeds.','','## Bootstrap discipline','All 10,000-repetition track bootstraps are conditional on this fixed scene and fixed diffusion realization; they are not diffusion-seed uncertainty intervals and support no cross-seed significance claim.','','## Preview companion','The frozen script SHA matches. A uniquely authoritative preview video input was not persisted/recovered, so no substitute was created; preview companion remains unresolved and track-supported metrics remain unresolved.','','## Stop rule','No generation, seed2, new candidate, GPU3, server-side Codex, or LLM API was used.']
(R/'PHASE0D_4D_R4C_FINAL.md').write_text('\n'.join(md)+'\n')
print(json.dumps({'result_sha256':sha(R/'PHASE0D_4D_R4C_RESULT.json'),'report_sha256':sha(R/'PHASE0D_4D_R4C_FINAL.md')}))
