#!/usr/bin/env python3
import json,hashlib
from pathlib import Path
R=Path('/workspace/DeformTransport_EvidenceV4_1/reports/phase0d/20260815_010000__phase0d_4d_r3_runtime_grid_reconciliation');base=json.loads((R/'FORMAL_RUNTIME_GRID_CONTRACT.json').read_text());eps=json.loads((R/'R3_SHARED_EPSILON_METADATA.json').read_text());sig=json.loads((R/'R3_SIGMA_POLICY_AMENDMENT.json').read_text())
common={'formal_overlay':{'wan_move_sha256':base['formal_overlay_wan_move_sha256'],'generate_sha256':'45f7323f22d7bb7d593b949fa48e6cf764d08cafeaf8863d726df9a663b21b85'},'preview':json.loads((R/'WAN_FORMAL_PREVIEW_LATENT_LINEAGE.json').read_text()),'epsilon':eps,'begin_index':15,'actual_native_sigma':sig['wan_sigma_argmin_value'],'actual_native_timestep':sig['wan_sigma_argmin_timestep'],'scheduler':'FlowUniPCMultistepScheduler','steps':40,'shift':3.0,'seed':0,'dtype':'bf16','resolution':'480*832 -> decoded 832x464','prompt':'Wind blows the hanging clothes. The motion is gentle, continuous, and rhythmic, driven by shifting airflow. Static camera, eye-level frontal view, natural fabric movement.','transport_variant':'v3d'}
c1=dict(common);c1['arm']='C1';c1['transport']={'K':0,'tracks':'k0_tracks.npy','visibility':'k0_visibility.npy','ids':'k0_ids.npy','depth':'k0_depth.npy','expected_writes':0}
c2=dict(common);c2['arm']='C2';c2['transport']={'K':1257,'tracks':'santa_material_tracks_correct.npy','visibility':'santa_material_visibility_correct.npy','ids':'santa_material_point_ids.npy','depth':'santa_authoritative_depth_81x1257.npy','expected_writes':'material transport'}
for n,x in [('C1_EFFECTIVE_PLANNED_MANIFEST.json',c1),('C2_EFFECTIVE_PLANNED_MANIFEST.json',c2)]: (R/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
diff=['transport.K','transport.tracks','transport.visibility','transport.ids','transport.depth','transport.expected_writes'];(R/'C_SEED0_PREREGISTRATION.json').write_text(json.dumps({'intended_scientific_difference_only':'MATERIAL_CARRIER_SET K0 vs K1257 Correct','C1_C2_UNEXPECTED_DIFFS':[],'expected_differences':diff,'uncontrolled_arm_specific_randomness':False},indent=2)+'\n')
